import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const valorant = localFont({
  src:"./fonts/Valorant.ttf",
  variable: "--font-geist-sans",
  weight: "100 900",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const header = (
    <header>
      <h1>
        <Header/>
      </h1>
    </header>
  )
  const footer = (
    <footer>
      <h1>
      <Footer/>
      </h1>
    </footer>
  )

  return (
    <html lang="en">
      <body className="">
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}

//w-full max-w-[1000px] mx-auto text-sm sm:text-base min-h-screen flex flex-col